In [1]:
import numpy as np
from qiskit import *
%matplotlib inline

In [2]:
def quantum_black_box(circ, q, option):
    if option==1:
        pass
    elif option==2:
        circ.x(q[1])
    elif option==3:
        circ.cx(q[0], q[1])
    elif option==4:
        circ.x(q[0])
        circ.cx(q[0], q[1])
        circ.x(q[0])
    return circ

In [3]:
# Deutsch's Algorithm
def deutsch_problem_circuit(option):
    q = QuantumRegister(2)
    circ = QuantumCircuit(q)
    circ.x(q[1])
    circ.h(q[0])
    circ.h(q[1])
    circ = quantum_black_box(circ, q, option)
    circ.h(q[0])
    return circ

In [4]:
circ1 = deutsch_problem_circuit(1)
circ1.draw()

In [5]:
circ2 = deutsch_problem_circuit(2)
circ2.draw()

In [6]:
circ3 = deutsch_problem_circuit(3)
circ3.draw()

In [7]:
circ4 = deutsch_problem_circuit(4)
circ4.draw()

In [8]:
# Import Aer
from qiskit import BasicAer

# Run the quantum circuit on a statevector simulator backend
backend = BasicAer.get_backend('statevector_simulator')

In [9]:
job1 = execute(circ1, backend)
result1 = job1.result()
result1.get_statevector()

array([ 0.70710678+0.j,  0.        +0.j, -0.70710678+0.j,  0.        +0.j])

In [10]:
job2 = execute(circ2, backend)
result2 = job2.result()
result2.get_statevector()

array([-0.70710678+0.j,  0.        +0.j,  0.70710678+0.j,  0.        +0.j])

In [11]:
job3 = execute(circ3, backend)
result3 = job3.result()
result3.get_statevector()

array([ 0.        +0.j,  0.70710678+0.j,  0.        +0.j, -0.70710678+0.j])

In [12]:
job4 = execute(circ4, backend)
result4 = job4.result()
result4.get_statevector()

array([ 0.        +0.j, -0.70710678+0.j,  0.        +0.j,  0.70710678+0.j])