In [1]:
import numpy as np
from qiskit import *
%matplotlib inline

In [2]:
def quantum_black_box(circ, n, q, option):
    if option==1:
        pass
    elif option==2:
        circ.x(q[n])
    elif option==3:
        circ.cx(q[0], q[n])
        circ.x(q[n])
    return circ

In [3]:
# Deutsch-Jozsa Algorithm
def deutsch_jozsa_problem_circuit(n, option):
    q = QuantumRegister(n+1)
    circ = QuantumCircuit(q)
    circ.x(q[n])
    for i in range(n):
        circ.h(q[i])
    circ.h(q[n])
    circ = quantum_black_box(circ, n, q, option)
    for i in range(n):
        circ.h(q[i])
    return circ

In [4]:
circ1 = deutsch_jozsa_problem_circuit(10, 1)
circ1.draw()

In [5]:
circ2 = deutsch_jozsa_problem_circuit(10, 2)
circ2.draw()

In [6]:
circ3 = deutsch_jozsa_problem_circuit(10, 3)
circ3.draw()

In [7]:
# Import Aer
from qiskit import BasicAer

# Run the quantum circuit on a statevector simulator backend
backend = BasicAer.get_backend('statevector_simulator')

In [8]:
job1 = execute(circ1, backend)
result1 = job1.result()
result1.get_statevector()

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, ...,
       0.        +0.j, 0.        +0.j, 0.        +0.j])

In [9]:
job2 = execute(circ2, backend)
result2 = job2.result()
result2.get_statevector()

array([-0.70710678+0.j,  0.        +0.j,  0.        +0.j, ...,
        0.        +0.j,  0.        +0.j,  0.        +0.j])

In [10]:
job3 = execute(circ3, backend)
result3 = job3.result()
result3.get_statevector()

array([ 0.        +0.j, -0.70710678+0.j,  0.        +0.j, ...,
        0.        +0.j,  0.        +0.j,  0.        +0.j])

In [16]:
np.where(result1.get_statevector()!=0)

(array([   0, 1024]),)

In [17]:
np.where(result2.get_statevector()!=0)

(array([   0, 1024]),)

In [18]:
np.where(result3.get_statevector()!=0)

(array([   1, 1025]),)

In [19]:
len(result1.get_statevector())

2048

In [21]:
format(1024, 'b')

'10000000000'

In [22]:
format(1025, 'b')

'10000000001'